name: Build and Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  DOTNET_VERSION: '8.0.x'
  PROJECT_NAME: 'SourceEngineFastDownloadTool'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Publish single executable
      run: |
        dotnet publish `
          --configuration ${{ env.BUILD_CONFIGURATION }} `
          --runtime win-x64 `
          --self-contained true `
          --output ./publish `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:IncludeAllContentForSelfExtract=true `
          -p:DebugType=None `
          -p:DebugSymbols=false `
          -p:EnableCompressionInSingleFile=true

    - name: Create release assets directory
      run: |
        mkdir release-assets
        Copy-Item -Path "config.json" -Destination "release-assets\" -ErrorAction SilentlyContinue
        Copy-Item -Path "filetypes.txt" -Destination "release-assets\" -ErrorAction SilentlyContinue
        Copy-Item -Path ".\publish\${{ env.PROJECT_NAME }}.exe" -Destination "release-assets\"
        # Create a batch file for easy execution
        Set-Content -Path ".\release-assets\RunFastDLTool.bat" -Value "@echo off`r`necho Starting Source Engine FastDownload Tool...`r`necho.`r`necho %~dp0${{ env.PROJECT_NAME }}.exe %*`r`npause"

    - name: Create ZIP archive
      run: |
        $version = "1.0.0"
        if ($env:GITHUB_REF -like "refs/tags/*") {
          $version = $env:GITHUB_REF -replace "refs/tags/v", ""
        }
        $zipName = "SourceEngineFastDownloadTool-v$version.zip"
        Compress-Archive -Path ".\release-assets\*" -DestinationPath $zipName -Force
        echo "ZIP_FILE=$zipName" >> $env:GITHUB_ENV

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SourceEngineFastDownloadTool
        path: ${{ env.ZIP_FILE }}

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: ${{ env.ZIP_FILE }}
        generate_release_notes: true
        draft: false
        prerelease: false
