name: Build and Release

on:
  push:
    tags:
      - 'v*' # Trigger on version tags like v1.0.0
  workflow_dispatch: # Allow manual triggering

env:
  DOTNET_VERSION: '8.0.x' # Use .NET 8.0
  PROJECT_NAME: 'SourceEngineFastDownloadTool'
  BUILD_CONFIGURATION: 'Release'

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore

    - name: Build application
      run: dotnet build --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    - name: Publish single executable
      run: |
        dotnet publish --configuration ${{ env.BUILD_CONFIGURATION }} \
          --runtime win-x64 \
          --self-contained true \
          --output ./publish \
          -p:PublishSingleFile=true \
          -p:IncludeNativeLibrariesForSelfExtract=true \
          -p:IncludeAllContentForSelfExtract=true \
          -p:DebugType=None \
          -p:DebugSymbols=false \
          -p:EnableCompressionInSingleFile=true

    - name: Create release assets directory
      run: |
        mkdir release-assets
        copy .\config.json .\release-assets\
        copy .\filetypes.txt .\release-assets\
        copy .\publish\${{ env.PROJECT_NAME }}.exe .\release-assets\
        # Create a batch file for easy execution
        echo @echo off > .\release-assets\RunFastDLTool.bat
        echo echo Starting Source Engine FastDownload Tool... >> .\release-assets\RunFastDLTool.bat
        echo echo. >> .\release-assets\RunFastDLTool.bat
        echo %~dp0${{ env.PROJECT_NAME }}.exe %* >> .\release-assets\RunFastDLTool.bat
        echo pause >> .\release-assets\RunFastDLTool.bat

    - name: Create ZIP archive
      run: |
        $version = "1.0.0"
        if ($env:GITHUB_REF -like "refs/tags/*") {
          $version = $env:GITHUB_REF -replace "refs/tags/v", ""
        }
        Compress-Archive -Path .\release-assets\* -DestinationPath "SourceEngineFastDownloadTool-v$version.zip" -Force

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: SourceEngineFastDownloadTool
        path: SourceEngineFastDownloadTool-v*.zip

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: SourceEngineFastDownloadTool-v*.zip
        generate_release_notes: true
        draft: false
        prerelease: false
